In [1]:
# !pip install pandas
# !pip install numpy

In [2]:
# !pip install matplotlib

In [3]:
# ! pip install scikit-learn

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [27]:
# import data
data = pd.read_csv('Housing.csv')
data

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [28]:
# to get info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [29]:
# drop the unwanted col
data = data.drop('stories',axis = 1)
data

price  area  bedrooms  bathrooms mainroad guestroom basement  \
0    13300000  7420         4          2      yes        no       no   
1    12250000  8960         4          4      yes        no       no   
2    12250000  9960         3          2      yes        no      yes   
3    12215000  7500         4          2      yes        no      yes   
4    11410000  7420         4          1      yes       yes      yes   
..        ...   ...       ...        ...      ...       ...      ...   
540   1820000  3000         2          1      yes        no      yes   
541   1767150  2400         3          1       no        no       no   
542   1750000  3620         2          1      yes        no       no   
543   1750000  2910         3          1       no        no       no   
544   1750000  3850         3          1      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 12 columns]

In [30]:
drop_col = ['prefarea','guestroom']
data = data.drop(drop_col,axis =1)

In [31]:
data

price  area  bedrooms  bathrooms mainroad basement hotwaterheating  \
0    13300000  7420         4          2      yes       no              no   
1    12250000  8960         4          4      yes       no              no   
2    12250000  9960         3          2      yes      yes              no   
3    12215000  7500         4          2      yes      yes              no   
4    11410000  7420         4          1      yes      yes              no   
..        ...   ...       ...        ...      ...      ...             ...   
540   1820000  3000         2          1      yes      yes              no   
541   1767150  2400         3          1       no       no              no   
542   1750000  3620         2          1      yes       no              no   
543   1750000  2910         3          1       no       no              no   
544   1750000  3850         3          1      yes       no              no   

    airconditioning  parking furnishingstatus  
0               yes        2        furnished  
1               yes        3        furnished  
2                no        2   semi-furnished  
3               yes        3        furnished  
4               yes        2        furnished  
..              ...      ...              ...  
540              no        2      unfurnished  
541              no        0   semi-furnished  
542              no        0      unfurnished  
543              no        0        furnished  
544              no        0      unfurnished  

[545 rows x 10 columns]

In [32]:
data.isna().sum()

price               0
area                0
bedrooms            0
bathrooms           0
mainroad            0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
furnishingstatus    0
dtype: int64

In [33]:
data= pd.get_dummies(data,drop_first = True)
data =data.astype(int)
data

price  area  bedrooms  bathrooms  parking  mainroad_yes  basement_yes  \
0    13300000  7420         4          2        2             1             0   
1    12250000  8960         4          4        3             1             0   
2    12250000  9960         3          2        2             1             1   
3    12215000  7500         4          2        3             1             1   
4    11410000  7420         4          1        2             1             1   
..        ...   ...       ...        ...      ...           ...           ...   
540   1820000  3000         2          1        2             1             1   
541   1767150  2400         3          1        0             0             0   
542   1750000  3620         2          1        0             1             0   
543   1750000  2910         3          1        0             0             0   
544   1750000  3850         3          1        0             1             0   

     hotwaterheating_yes  airconditioning_yes  \
0                      0                    1   
1                      0                    1   
2                      0                    0   
3                      0                    1   
4                      0                    1   
..                   ...                  ...   
540                    0                    0   
541                    0                    0   
542                    0                    0   
543                    0                    0   
544                    0                    0   

     furnishingstatus_semi-furnished  furnishingstatus_unfurnished  
0                                  0                             0  
1                                  0                             0  
2                                  1                             0  
3                                  0                             0  
4                                  0                             0  
..                               ...                           ...  
540                                0                             1  
541                                1                             0  
542                                0                             1  
543                                0                             0  
544                                0                             1  

[545 rows x 11 columns]

In [34]:
data.rename(columns={'furnishingstatus_semi-furnished':'furnishingstatus_semi_furnished'}, inplace =True)
data

price  area  bedrooms  bathrooms  parking  mainroad_yes  basement_yes  \
0    13300000  7420         4          2        2             1             0   
1    12250000  8960         4          4        3             1             0   
2    12250000  9960         3          2        2             1             1   
3    12215000  7500         4          2        3             1             1   
4    11410000  7420         4          1        2             1             1   
..        ...   ...       ...        ...      ...           ...           ...   
540   1820000  3000         2          1        2             1             1   
541   1767150  2400         3          1        0             0             0   
542   1750000  3620         2          1        0             1             0   
543   1750000  2910         3          1        0             0             0   
544   1750000  3850         3          1        0             1             0   

     hotwaterheating_yes  airconditioning_yes  \
0                      0                    1   
1                      0                    1   
2                      0                    0   
3                      0                    1   
4                      0                    1   
..                   ...                  ...   
540                    0                    0   
541                    0                    0   
542                    0                    0   
543                    0                    0   
544                    0                    0   

     furnishingstatus_semi_furnished  furnishingstatus_unfurnished  
0                                  0                             0  
1                                  0                             0  
2                                  1                             0  
3                                  0                             0  
4                                  0                             0  
..                               ...                           ...  
540                                0                             1  
541                                1                             0  
542                                0                             1  
543                                0                             0  
544                                0                             1  

[545 rows x 11 columns]

In [36]:
# to split input and output
independent = data[['area', 'bedrooms', 'bathrooms', 'parking', 'mainroad_yes',
       'basement_yes', 'hotwaterheating_yes', 'airconditioning_yes',
       'furnishingstatus_semi_furnished', 'furnishingstatus_unfurnished']]
dependent = data[['price']]

In [37]:
# split data into training and  testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.30,random_state=0)
x_train,x_test,y_train,y_test

(      area  bedrooms  bathrooms  parking  mainroad_yes  basement_yes  \
 454   4500         3          1        0             1             0   
 392   3990         3          1        0             1             0   
 231   4320         3          1        0             1             0   
 271   1905         5          1        0             0             1   
 250   3510         3          1        0             1             0   
 ..     ...       ...        ...      ...           ...           ...   
 70    4000         3          2        0             1             1   
 277  10360         2          1        1             1             0   
 9     5750         3          2        1             1             0   
 359   3600         3          1        1             1             0   
 192   6600         3          1        0             1             1   
 
      hotwaterheating_yes  airconditioning_yes  \
 454                    0                    1   
 392                  

In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


In [39]:
# y_test

In [40]:
from sklearn.linear_model import LinearRegression
regressor_f = LinearRegression()
regressor_f.fit(x_train,y_train)

LinearRegression()

In [43]:
weight = regressor_f.coef_
bias = regressor_f.intercept_
print("The weight :",weight, "and the bias: ",bias)

The weight : [[ 580960.43437061  235054.26412019  560841.75853287   98375.9310836
   262448.02598656  188950.50359097  245342.674538    490540.30287133
   -81361.60613646 -261741.70612335]] and the bias:  [4768119.26509186]


In [44]:
test_pred = regressor_f.predict(x_test)
test_pred

array([[ 3999156.96670837],
       [ 6166015.44263223],
       [ 4935602.63254285],
       [ 7965200.26595179],
       [ 2787405.32242709],
       [ 6781690.62226094],
       [ 3508954.52644874],
       [ 2910328.64797799],
       [ 2966590.02693423],
       [ 8117164.23445487],
       [ 6450343.04986983],
       [ 3874807.99228534],
       [ 3959739.71126621],
       [ 4892984.18342867],
       [ 4705913.54510421],
       [ 2095056.85329734],
       [ 4056245.63057269],
       [ 4316171.72683825],
       [ 3085945.15283844],
       [ 4971270.52373716],
       [ 6503903.89911263],
       [ 6798171.81142261],
       [ 5058599.93056547],
       [ 2650954.86713141],
       [ 4440324.52756687],
       [ 6239818.95567591],
       [ 5229827.48394575],
       [ 5371332.04252552],
       [ 6237038.45652398],
       [ 6041613.52747007],
       [ 3621602.31159885],
       [ 5444791.15549586],
       [ 6290948.74515277],
       [ 3122006.11540226],
       [ 4280123.42861116],
       [ 5489887.448

In [45]:
from sklearn.metrics import r2_score
r2_score_value = r2_score(y_test,test_pred)
r2_score_value

0.6680735102867936

In [46]:
from sklearn.svm import SVR
regressor = SVR(kernel ='linear')
regressor.fit(x_train,y_train)

C:\Users\kathi\anaconda3\envs\ml_projects\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(kernel='linear')

In [47]:
test_pred_svm = regressor.predict(x_test)
test_pred_svm

array([4381426.09023504, 4382238.88626948, 4381866.25521038,
       4382364.57491343, 4380873.99810306, 4382090.77380268,
       4381250.57309647, 4381175.43264789, 4380954.20037028,
       4382696.81657361, 4381959.05521649, 4381320.35855554,
       4381595.92313324, 4381715.05252711, 4381823.46880045,
       4380599.69924103, 4381562.18537107, 4381620.41585433,
       4381245.37662517, 4381720.95713877, 4382261.9507118 ,
       4381800.38888139, 4381840.59599261, 4380853.30321633,
       4381483.17259148, 4382009.73127079, 4382118.85925957,
       4382003.77509893, 4382070.75496811, 4382059.10367949,
       4381413.2511819 , 4381666.37102456, 4382176.91997366,
       4381001.59449741, 4381317.54726126, 4382112.38426034,
       4382192.98974373, 4381558.76182901, 4380946.79596012,
       4381094.74160897, 4382488.04368282, 4381627.54795232,
       4381777.21080703, 4381400.14310739, 4381220.95176701,
       4382174.50563481, 4381592.04834027, 4380899.4532821 ,
       4381751.56226479,

In [48]:
from sklearn.metrics import r2_score
r2_score_value_svm = r2_score(y_test,test_pred_svm)
r2_score_value_svm

-0.04154557172223661

In [49]:

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state= 0)
regressor.fit(x_train,y_train)

DecisionTreeRegressor(random_state=0)

In [50]:
test_pred_dt = regressor.predict(x_test)
test_pred_dt

array([ 2660000.,  5040000.,  5950000.,  5040000.,  3500000.,  7840000.,
        5250000.,  5145000.,  2782500.,  6790000.,  5775000.,  2800000.,
        4515000.,  5243000.,  5243000.,  2240000.,  5033000.,  5600000.,
        3640000.,  3640000., 12215000.,  9681000.,  5740000.,  2100000.,
        6510000.,  4025000.,  5229000.,  4935000.,  4200000.,  4760000.,
        3150000.,  4900000.,  5320000.,  3423000.,  3640000.,  8400000.,
        5950000.,  3640000.,  4515000.,  2240000.,  8575000.,  5600000.,
        9800000.,  2940000.,  3395000.,  6580000.,  4651500.,  3423000.,
        4900000.,  5873000.,  3780000., 12250000.,  2240000.,  3710000.,
        3465000.,  3080000.,  9240000.,  4907000.,  3710000.,  5215000.,
        3500000.,  5600000.,  3640000.,  7210000.,  3353000.,  5110000.,
        8080940.,  2590000.,  5250000.,  8400000.,  3850000.,  8400000.,
        4550000.,  4340000.,  4445000.,  4235000.,  2100000.,  6790000.,
        4403000.,  3710000.,  3850000.,  5215000., 

In [51]:
from sklearn.metrics import r2_score
r2_score_dt = r2_score(y_test,test_pred_dt)
r2_score_dt

0.11717224893916989

In [52]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x_train,y_train)



C:\Users\kathi\anaconda3\envs\ml_projects\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(n_estimators=10, random_state=0)

In [53]:
test_pred_rf = regressor.predict(x_test)
test_pred_rf

array([3878700.        , 5343800.        , 4660250.        ,
       5550300.        , 3438400.        , 7406000.        ,
       3806250.        , 3488100.        , 2623833.33333333,
       9618000.        , 5946500.        , 3178000.        ,
       4225900.        , 5418700.        , 5432000.        ,
       2388715.        , 4640300.        , 5474700.        ,
       3390100.        , 4203500.        , 8333500.        ,
       6330100.        , 5512500.        , 3069500.        ,
       5764500.        , 4969300.        , 5261200.        ,
       5104400.        , 4315500.        , 6132000.        ,
       3906000.        , 4163705.        , 6394500.        ,
       3193400.        , 4100600.        , 5539800.        ,
       5550300.        , 4126500.        , 3395000.        ,
       3472000.        , 9282000.        , 6051500.        ,
       6968500.        , 5276600.        , 3444000.        ,
       6835500.        , 4291700.        , 3334800.        ,
       5064500.        ,

In [54]:
from sklearn.metrics import r2_score
r2_score_value_rf = r2_score(y_test,test_pred_rf)
r2_score_value_rf

0.5453431061603313

In [55]:
!pip install xgboost

In [56]:
import xgboost as xgb
from xgboost import XGBRegressor
regressor = XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,max_depth = 5, alpha = 10, n_estimators = 10)
regressor.fit(x_train,y_train)

C:\Users\kathi\anaconda3\envs\ml_projects\Lib\site-packages\xgboost\core.py:158: UserWarning: [12:57:02] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\objective\regression_obj.cu:227: reg:linear is now deprecated in favor of reg:squarederror.
  warnings.warn(smsg, UserWarning)


XGBRegressor(alpha=10, base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.3, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=5, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=10, n_jobs=None,
             num_parallel_tree=None, ...)

In [57]:
test_pred = regressor.predict(x_test)
test_pred

array([4390332. , 5226346. , 4573609.5, 5171682.5, 4179821.8, 5791040. ,
       4371725.5, 4459420.5, 3845938.8, 6226843. , 6058206. , 4100786. ,
       4564181. , 5124591. , 5288250.5, 3890975.2, 4287894.5, 5244238. ,
       4152646.2, 4463120.5, 5477966. , 5991855. , 4948045. , 4018766.2,
       5242839.5, 4552125. , 5334740. , 5275466.5, 4277990. , 5661569. ,
       4219714. , 4286239. , 5586732.5, 4150618.2, 4605936.5, 5014763. ,
       5620609. , 4152646.2, 3806349. , 4420961. , 6012769.5, 5066816.5,
       5465032. , 4610472.5, 4418889. , 5735056. , 4909580. , 4095678.5,
       4791871. , 5397556. , 4572081.5, 5949646. , 4167104.8, 3992913.5,
       4583692. , 4508169.5, 5526428. , 4651117. , 3957540.5, 5053679. ,
       5253676. , 5481873.5, 4216120.5, 5934566.5, 3683681.8, 4347026. ,
       5685928.5, 4120909.2, 4492937.5, 5586690.5, 4095889. , 5527577.5,
       4454159. , 5495097.5, 4173589.2, 3934298.8, 4134784. , 5714236. ,
       3890975.2, 4020600. , 4095889. , 5933095. , 

In [58]:
from sklearn.metrics import r2_score
r2_score_xg = r2_score(y_test, test_pred)
r2_score_xg

0.4389601945877075

In [59]:
import pickle
filename ='Houseprice_pred.sav'

In [60]:
pickle.dump(regressor_f,open(filename,'wb'))
load_model = pickle.load(open('Houseprice_pred.sav','rb'))

In [61]:
data.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'parking', 'mainroad_yes',
       'basement_yes', 'hotwaterheating_yes', 'airconditioning_yes',
       'furnishingstatus_semi_furnished', 'furnishingstatus_unfurnished'],
      dtype='object')

In [62]:
preinput = sc.transform([[7420,4,2,2,1,0,0,1,0,0]])
preinput

C:\Users\kathi\anaconda3\envs\ml_projects\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 1.19307749,  1.47896994,  1.48838327,  1.46571002,  0.3931227 ,
        -0.71128676, -0.21610946,  1.42260659, -0.84629558, -0.6946152 ]])

In [67]:
result = load_model.predict(preinput)
result

array([[7652093.36366038]])

In [65]:
# !pip install numpy==1.17.4
# !pip install pandas==0.25.3
# !pip install scikit-learn==0.21.3
# !pip install matplotlib==3.1.1
# !pip install django==3.0.2
# !pip install django-crispy-forms==1.8.1
# !pip install shap==0.34.0
# !pip install pdpbox==0.2.0
# !pip install eli5==0.10.1

In [66]:
result = load_model.predict([[7420,4,2,2,1,0,0,1,0,0]])
result

array([[4.31850618e+09]])

In [ ]:
!pip uninstall numpy==2.1.1

In [68]:
import numpy as np
print(np.__version__)


2.1.1
